#div pgm

# num1=int(input("Enter 1st no:"))
# num2=int(input("Enter 2nd no:"))
# print(num1/num2)

#zero division error   5/0

# num1=int(input("Enter 1st no:"))
# num2=int(input("Enter 2nd no:"))
# try:
#     print(num1/num2)
# except:
#     print("Exception occured..")

#index out of range

# lst=[1,2,3]
# try:
#     n=int(input("Enter the index"))
#     print(lst[n])
# except:
#     print("Exception occured..")
# finally:
#     print("Inside finally..")

#finally block work with any block

#type exception
# try:
#     a=int(input())
#     b=int(input())
#     print(a+b)
# except:
#     print("Exception occured..")
# finally:
#   print("In finally..")

#at a time in such cases try and except and finally work together



